name: file_type
description: get file type according to file header

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.1.0

environment:
  sdk: ">=2.17.5 <3.0.0"


dev_dependencies:
  lints: ^2.0.0
dependencies:
  collection: ^1.17.0
  tuple: ^2.0.0
